# Generated by Django 6.1.1 on 2026-09-28 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='+91 98765 43210', max_length=20)),
                ('pan_number', models.CharField(blank=True, default='ABCDE1234F', max_length=15)),
                ('aadhaar_last4', models.CharField(blank=True, default='5678', max_length=4)),
                ('address', models.CharField(blank=True, default='42, Marine Drive, Nariman Point', max_length=255)),
                ('city', models.CharField(blank=True, default='Mumbai', max_length=100)),
                ('state', models.CharField(blank=True, default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(blank=True, default='400021', max_length=10)),
                ('kyc_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Verification'), ('in_review', 'In Review'), ('rejected', 'Rejected')], default='verified', max_length=20)),
                ('account_tier', models.CharField(choices=[('standard', 'Standard'), ('gold', 'Gold Privilege'), ('platinum', 'Platinum Elite')], default='platinum', max_length=20)),
                ('avatar_color', models.CharField(default='from-blue-600 to-indigo-600', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
