# Generated by Django 6.1.1 on 2026-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar_color',
            field=models.CharField(default='from-blue-600 to-indigo-600', max_length=100),
        ),
    ]
